# This dockerfile uses the gradle image
# VERSION 1
# Author: wade

FROM centos

MAINTAINER wade wadechen@outlook.com

RUN dnf install -y git\
    && git clone https://github.com/wadeee/oftenshell.git ~/oftenshell

CMD ["/sbin/init"]
